/**
 * Relock's permanent dark material language.
 *
 * These tokens are intentionally semantic: feature UI can describe a role
 * (hero, action, ambient glow) without owning raw visual values.
 */
export const relockMaterial = {
  colors: {
    surfaceHeroTop: '#151629',
    surfaceHeroBottom: '#0D0E19',
    surfacePanelTop: '#131522',
    surfacePanelBottom: '#0B0C14',
    surfaceInteractiveTop: '#1B1C2C',
    surfaceInteractiveBottom: '#11121D',
    surfaceHighlight: 'rgba(255, 255, 255, 0.09)',
    surfaceHighlightSoft: 'rgba(255, 255, 255, 0.04)',
    borderSubtle: 'rgba(192, 188, 255, 0.11)',
    borderInteractive: 'rgba(224, 220, 255, 0.14)',
    textPrimary: '#F7F6FC',
    textSecondary: '#B6B6C7',
    textTertiary: '#85869A',
    accentViolet: '#A78BFA',
    accentVioletDeep: '#7357DC',
    accentBlue: '#7C89F8',
    accentSoft: 'rgba(167, 139, 250, 0.24)',
    onAccent: '#FFFFFF',
    onBrightAccent: '#171329',
    moonHalo: 'rgba(146, 121, 244, 0.24)',
    moonHaloSolid: '#9279F4',
    moonHaloSoft: 'rgba(113, 94, 211, 0.08)',
    shadow: '#000000',
    transparent: 'rgba(0, 0, 0, 0)',
    alertText: '#FFD6DD',
    alertTextMuted: 'rgba(255, 214, 221, 0.76)',
    alertBackground: 'rgba(251, 113, 133, 0.1)',
    alertBorder: 'rgba(251, 113, 133, 0.22)',
    blockingCanvas: '#030504',
    blockingCanvasTop: '#070A0B',
    blockingSurface: '#090B0B',
    blockingSurfaceRaised: '#111312',
    blockingSurfaceActiveTop: '#1B1524',
    blockingSurfaceActiveMiddle: '#131018',
    blockingSurfaceActiveBottom: '#090A0A',
    blockingSurfaceActiveBloom: '#49345E',
    blockingSurfaceCool: '#0C0E11',
    // Les feuilles restent neutres et nocturnes : la lumière violette vient
    // d'un foyer local, jamais d'un grand aplat gris-violet.
    blockingSheetSurfaceTop: '#302E35',
    blockingSheetSurface: '#242429',
    blockingSheetCard: '#302F36',
    blockingBorder: 'rgba(255, 255, 255, 0.07)',
    blockingBorderStrong: 'rgba(198, 181, 255, 0.16)',
    blockingAccent: '#8B5CFF',
    blockingAccentLight: '#C6B5FF',
    blockingAccentMedium: '#4A4259',
    blockingAccentDark: '#2A2433',
    blockingAccentTint: 'rgba(139, 92, 255, 0.12)',
    blockingAccentTintStrong: 'rgba(139, 92, 255, 0.28)',
    // Remplissage de la barre d'avancement : nettement plus dense que le
    // fond de la pilule, sinon la progression ne se voit pas.
    blockingProgressFill: 'rgba(139, 92, 255, 0.45)',
    blockingPill: 'rgba(24, 26, 25, 0.9)',
    blockingInkMuted: '#A4A4AA',
    blockingLockedAppMark: 'rgba(255, 255, 255, 0.96)',
    blockingUnlockedAppMark: 'rgba(255, 255, 255, 0.78)',
    blockingAppMarkContrast: 'rgba(0, 0, 0, 0.78)',
    blockingImageShade: 'rgba(3, 5, 4, 0.34)',
    blockingImageChrome: 'rgba(3, 5, 4, 0.7)',
    blockingModalBackdrop: 'rgba(3, 5, 4, 0.84)',
    // Rouge des actions irréversibles : une seule teinte, déclinée en
    // remplissage, halo et bordure, pour que « supprimer » se reconnaisse
    // partout à la même couleur.
    blockingDanger: '#FB7185',
    blockingDangerBright: '#FF9AAC',
    blockingDangerTint: 'rgba(251, 113, 133, 0.16)',
    blockingDangerWash: 'rgba(251, 113, 133, 0.34)',
    blockingDangerBorder: 'rgba(251, 113, 133, 0.44)',
    // La feuille destructrice est lie-de-vin presque noire. Le bouton garde le
    // rouge saturé : les deux ne peuvent plus se confondre.
    blockingDangerCanvas: '#180A10',
    blockingDangerDeep: '#67182D',
    blockingDangerSurface: '#D54861',
    // Avertissement : ni le violet de la marque (qui invite), ni le rouge de
    // la suppression (qui détruit) — l'ambre dit « lis avant de continuer ».
    blockingWarning: '#F2B155',
    blockingWarningTint: 'rgba(242, 177, 85, 0.16)',
    blockingWarningBorder: 'rgba(242, 177, 85, 0.46)',
    // Verre des commandes posées sur une feuille (croix, « Modifier »).
    blockingGlass: 'rgba(255, 255, 255, 0.11)',
    // Verre CLAIR des actions secondaires posées sur une image : il se
    // distingue du dégradé violet, réservé à l'action principale de l'écran.
    blockingGlassBright: 'rgba(255, 255, 255, 0.24)',
    blockingGlassBrightEdge: 'rgba(255, 255, 255, 0.42)',
  },
  radius: {
    hero: 28,
    panel: 26,
    visual: 28,
    functional: 20,
    action: 18,
    button: 17,
    compact: 12,
    capsule: 999,
  },
  layout: {
    contentMaxWidth: 540,
    screenHorizontal: 16,
    headerTop: 12,
    headerBottom: 12,
    headerLogoWidth: 126,
    headerLogoHeight: 24,
    headerFlameSize: 32,
    headerActionSize: 44,
    headerIconSize: 24,
    welcomeCopyGap: 5,
    welcomeBottom: 8,
    heroMinHeight: 300,
    heroMaxHeight: 323,
    heroAspectRatio: 0.823,
    heroPaddingHorizontal: 27,
    heroPaddingTop: 48,
    heroPaddingBottom: 24,
    heroCopyWidth: 216,
    heroMoonSize: 190,
    heroMoonRight: -10,
    heroMoonTop: 26,
    heroTitleBottom: 10,
    heroDescriptionBottom: 14,
    primaryActionHeight: 54,
    primaryActionHorizontal: 18,
    primaryActionArrowRight: 18,
    sectionGap: 18,
    panelPadding: 12,
    panelTitleHorizontal: 4,
    panelTitleBottom: 6,
    quickActionMaxHeight: 72,
    quickActionAspectRatio: 0.198,
    quickActionGap: 8,
    quickActionHorizontal: 16,
    quickIconSize: 50,
    quickDecorationSize: 92,
    quickDecorationRight: 8,
    quickChevronSize: 20,
    bottomNavigationClearance: 49,
    scrollBottom: 28,
    blockingTypeCardMinHeight: 148,
    blockingTypeGlyphSize: 32,
    blockingTypeChevronSize: 20,
    blockingTemplateCardMinHeight: 224,
    blockingLockedTileSize: 68,
    blockingScrollBottom: 112,
    blockingCardColumnWidth: '48.4%',
  },
  typography: {
    welcomeTitleSize: 16,
    welcomeTitleLineHeight: 22,
    welcomeBodySize: 15,
    welcomeBodyLineHeight: 21,
    heroTitleSize: 24,
    heroTitleLineHeight: 29,
    heroTitleLetterSpacing: -0.45,
    heroBodySize: 15,
    heroBodyLineHeight: 21,
    buttonSize: 16,
    buttonLineHeight: 22,
    sectionTitleSize: 18,
    sectionTitleLineHeight: 24,
    quickTitleSize: 16,
    quickTitleLineHeight: 22,
    quickDetailSize: 13,
    quickDetailLineHeight: 18,
    blockingTitleSize: 34,
    blockingTitleLineHeight: 41,
    blockingSectionSize: 20,
    blockingSectionLineHeight: 26,
    blockingCardTitleSize: 17,
    blockingCardTitleLineHeight: 22,
    blockingCardBodySize: 14,
    blockingCardBodyLineHeight: 19,
    blockingMetaSize: 13,
    blockingMetaLineHeight: 18,
    blockingTypeTitleSize: 15,
    blockingTypeTitleLineHeight: 20,
    blockingCompactTitleSize: 13,
    blockingCompactTitleLineHeight: 17,
    blockingCompactBodySize: 12,
    blockingCompactBodyLineHeight: 15,
    blockingSectionLetterSpacing: -0.35,
    blockingTitleLetterSpacing: -0.8,
  },
  opacity: {
    decorative: 0.22,
    decorativeStrong: 0.34,
    disabled: 0.52,
    blockingAmbient: 0.08,
  },
  shadow: {
    hero: {
      elevation: 8,
      shadowColor: '#000000',
      shadowOpacity: 0.3,
      shadowRadius: 20,
      shadowOffset: { width: 0, height: 12 },
    },
    panel: {
      elevation: 5,
      shadowColor: '#000000',
      shadowOpacity: 0.22,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 8 },
    },
    action: {
      elevation: 3,
      shadowColor: '#000000',
      shadowOpacity: 0.2,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 5 },
    },
    glow: {
      elevation: 5,
      shadowColor: '#8F73EF',
      shadowOpacity: 0.28,
      shadowRadius: 13,
      shadowOffset: { width: 0, height: 5 },
    },
    blockingSubtle: {
      elevation: 1,
      shadowColor: '#000000',
      shadowOpacity: 0.12,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 3 },
    },
    blockingGlow: {
      elevation: 1,
      shadowColor: '#8B5CFF',
      shadowOpacity: 0.08,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
    },
  },
} as const

export type RelockMaterial = typeof relockMaterial
